### Listar os Elementos Calculados
GET https://localhost:5001/elementos_quimicos/elemento/listar

### Calcular um Elemento Químico
POST https://localhost:5001/elementos_quimicos/elemento/cadastrar
Content-Type: application/json

{
    "nome" : "Ca",
    "massa" : "20"
    
}api

### Buscar um Elemento Químico pelo seu Id
GET https://localhost:5001/elementos_quimicos/elemento/buscar/

### Deletar um Elementos Químico pelo Id
DELETE https://localhost:5001/elementos_quimicos/elemento/deletar/

### Alterar um Elementos Químico
PATCH  https://localhost:5001/elementos_quimicos/elemento/alterar
Content-Type: application/json

{
    "id" :  ,
    "nome" : "",
    "massa" : ""
}